### ISSUE TITLE
read this if you want to make encryption work

### ISSUE THREAD

**Issue by jututt** [Hamza-Megahed/hg532#6]
add comment at the beginning of line 118
like this
`#	check_config(new_config_file)`

enjoy

**Comment by Red-A-Hawk** [comment]
السلام عليكم

**Comment by mitota** [comment]
يا خويا بحرتلي في حاجة

**Comment by mitota** [comment]
عطيني مثال مثلا انا ملف اسمه 1.conf

**Comment by mitota** [comment]
و ملف موجود في مجلد home
