### ISSUE TITLE
Does this work for HG532d too?

### ISSUE THREAD

**Issue by ScotchandDry** [Hamza-Megahed/hg532#9]
Hi Hamza. Sorry to resurrect an old thread. Should this work for HG532d? I am getting "verifying signature... Signature not ok...exiting" I am trying to decrypt my config file to move to a new router. Any help would be appreciated.. Thanks.

**Comment by Hamza-Megahed** [comment]
can you send a sample file to test it ?

**Comment by ScotchandDry** [comment]
Hi Hamza. I have already got rid of that ADSL modem. Thanks anyways..
